# please run `bazel run //practical_exercises/10_day_practice/day1:union`
# please run `bazel run //practical_exercises/10_day_practice/day1:print`
# please run `bazel run //practical_exercises/10_day_practice/day1:annotate`
# please run `bazel run //practical_exercises/10_day_practice/day1:runnian`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "union",
    srcs = ["union.cpp"],
)
cc_binary(
    name = "print",
    srcs = ["print.cpp"],
)
cc_binary(
    name = "annotate",
    srcs = ["annotate.cpp"],
)
cc_binary(
    name = "runnian",
    srcs = ["runnian.cpp"],
)
