# please run `bazel run //practical_exercises/10_day_practice/day10/file:12-9`
# please run `bazel run //practical_exercises/10_day_practice/day10/file:12-6`
# please run `bazel run //practical_exercises/10_day_practice/day10/file:10-4`
# please run `bazel run //practical_exercises/10_day_practice/day10/file:12-2`
# please run `bazel run //practical_exercises/10_day_practice/day10/file:practice`
# please run `bazel run //practical_exercises/10_day_practice/day10/file:12-1`
# please run `bazel run //practical_exercises/10_day_practice/day10/file:12-5`
# please run `bazel run //practical_exercises/10_day_practice/day10/file:12-3`
# please run `bazel run //practical_exercises/10_day_practice/day10/file:12-7`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "12-9",
    srcs = ["12-9.cpp"],
)
cc_binary(
    name = "12-6",
    srcs = ["12-6.cpp"],
)
cc_binary(
    name = "10-4",
    srcs = ["10-4.cpp"],
)
cc_binary(
    name = "12-2",
    srcs = ["12-2.cpp"],
)
cc_binary(
    name = "practice",
    srcs = ["practice.cpp"],
)
cc_binary(
    name = "12-1",
    srcs = ["12-1.cpp"],
)
cc_binary(
    name = "12-5",
    srcs = ["12-5.cpp"],
)
cc_binary(
    name = "12-3",
    srcs = ["12-3.cpp"],
)
cc_binary(
    name = "12-7",
    srcs = ["12-7.cpp"],
)
