# please run `bazel run basic_content/func_pointer:func_pointer`
load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "func_pointer",
    srcs = ["func_pointer.cpp"],
    copts = ["-std=c++11"]
)