# please run `bazel run //learn_class/modern_cpp_30/compilerpoly:template`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "template",
    srcs = ["template.cpp"],
    copts = ["-std=c++17"],
)
