# please run `bazel run //codingStyleIdioms/4_copy-swap:copy-swapAndADL`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "copy-swapAndADL",
    srcs = ["copy-swapAndADL.cpp"],
    copts = ["-std=c++11"],
)
