# please run `bazel run //practical_exercises/10_day_practice/day7/binary_operator:operator`
# please run `bazel run //practical_exercises/10_day_practice/day7/binary_operator:friend_operator`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "operator",
    srcs = ["operator.cpp"],
)
cc_binary(
    name = "friend_operator",
    srcs = ["friend_operator.cpp"],
)
