# please run `bazel run //practical_exercises/10_day_practice/day7/equal_operator:equal_operator`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "equal_operator",
    srcs = ["equal_operator.cpp"],
)
