# please run `bazel run //practical_exercises/10_day_practice/day7/subscript_operator:example`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "exexampleample1",
    srcs = ["example.cpp"],
)
