# please run `bazel run //practical_exercises/10_day_practice/day3:static_member1`
# please run `bazel run //practical_exercises/10_day_practice/day3:swap`
# please run `bazel run //practical_exercises/10_day_practice/day3:pratice`
# please run `bazel run //practical_exercises/10_day_practice/day3:static_member2`
# please run `bazel run //practical_exercises/10_day_practice/day3:predeclare`
# please run `bazel run //practical_exercises/10_day_practice/day3:inline`
# please run `bazel run //practical_exercises/10_day_practice/day3:static_data`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "static_member1",
    srcs = ["static_member1.cpp"],
)
cc_binary(
    name = "swap",
    srcs = ["swap.cpp"],
)
cc_binary(
    name = "pratice",
    srcs = ["pratice.cpp"],
)
cc_binary(
    name = "static_member2",
    srcs = ["static_member2.cpp"],
)
cc_binary(
    name = "predeclare",
    srcs = ["predeclare.cpp"],
)
cc_binary(
    name = "inline",
    srcs = ["inline.cpp"],
)
cc_binary(
    name = "static_data",
    srcs = ["static_data.cpp"],
)
