# please run `bazel run //practical_exercises/10_day_practice/day4/const:obj_func`
# please run `bazel run //practical_exercises/10_day_practice/day4/const:obj_ref`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "obj_func",
    srcs = ["obj_func.cpp"],
)
cc_binary(
    name = "obj_ref",
    srcs = ["obj_ref.cpp"],
)
