# please run `bazel run //learn_class/modern_cpp_30/exception:exception`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "exception",
    srcs = ["exception.cpp"],
    copts = ["-std=c++11"],
)
