# please run `bazel run //practical_exercises/10_day_practice/day8/func:main`
# please run `bazel run //practical_exercises/10_day_practice/day8/func:max_spec`
# please run `bazel run //practical_exercises/10_day_practice/day8/func:max`
# please run `bazel run //practical_exercises/10_day_practice/day8/func:sort`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "main",
    srcs = ["main.cpp"],
)
cc_binary(
    name = "max_spec",
    srcs = ["max_spec.cpp"],
)
cc_binary(
    name = "max",
    srcs = ["max.cpp"],
)
cc_binary(
    name = "sort",
    srcs = ["sort.cpp"],
)
