# please run `bazel run //practical_exercises/10_day_practice/day5/ctor_dtor:param`
# please run `bazel run //practical_exercises/10_day_practice/day5/ctor_dtor:noctor`
# please run `bazel run //practical_exercises/10_day_practice/day5/ctor_dtor:cseq`
# please run `bazel run //practical_exercises/10_day_practice/day5/ctor_dtor:ctor`
# please run `bazel run //practical_exercises/10_day_practice/day5/ctor_dtor:ctor_d`
# please run `bazel run //practical_exercises/10_day_practice/day5/ctor_dtor:seq`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "param",
    srcs = ["param.cpp"],
)
cc_binary(
    name = "noctor",
    srcs = ["noctor.cpp"],
)
cc_binary(
    name = "cseq",
    srcs = ["cseq.cpp"],
)
cc_binary(
    name = "ctor",
    srcs = ["ctor.cpp"],
)
cc_binary(
    name = "ctor_d",
    srcs = ["ctor_d.cpp"],
)
cc_binary(
    name = "seq",
    srcs = ["seq.cpp"],
)
