# please run `bazel run basic_content/virtual/set2:default_arg`
load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "default_arg",
    srcs = ["default_arg.cpp"],
    copts = ["-std=c++11"]
)