# please run `bazel run //practical_exercises/10_day_practice/day5/virtual:example2`
# please run `bazel run //practical_exercises/10_day_practice/day5/virtual:init`
# please run `bazel run //practical_exercises/10_day_practice/day5/virtual:seq`
# please run `bazel run //practical_exercises/10_day_practice/day5/virtual:example1`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "example2",
    srcs = ["example2.cpp"],
)
cc_binary(
    name = "init",
    srcs = ["init.cpp"],
)
cc_binary(
    name = "seq",
    srcs = ["seq.cpp"],
)
cc_binary(
    name = "example1",
    srcs = ["example1.cpp"],
)
