# please run `bazel run //cpp2.0/cpp11:variadic7`
# please run `bazel run //cpp2.0/cpp11:variadic3_4`
# please run `bazel run //cpp2.0/cpp11:variadic2`
# please run `bazel run //cpp2.0/cpp11:variadic6`
# please run `bazel run //cpp2.0/cpp11:variadic5`
# please run `bazel run //cpp2.0/cpp11:variadic`
# please run `bazel run //cpp2.0/cpp11:variadic1`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "variadic7",
    srcs = ["variadic7.cpp"],
)
cc_binary(
    name = "variadic3_4",
    srcs = ["variadic3_4.cpp"],
)
cc_binary(
    name = "variadic2",
    srcs = ["variadic2.cpp"],
)
cc_binary(
    name = "variadic6",
    srcs = ["variadic6.cpp"],
)
cc_binary(
    name = "variadic5",
    srcs = ["variadic5.cpp"],
)
cc_binary(
    name = "variadic",
    srcs = ["variadic.cpp"],
)
cc_binary(
    name = "variadic1",
    srcs = ["variadic1.cpp"],
)
