# please run `bazel run //practical_exercises/10_day_practice/day10/file/input:getline`
# please run `bazel run //practical_exercises/10_day_practice/day10/file/input:get2`
# please run `bazel run //practical_exercises/10_day_practice/day10/file/input:get`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "getline",
    srcs = ["getline.cpp"],
)
cc_binary(
    name = "get2",
    srcs = ["get2.cpp"],
)
cc_binary(
    name = "get",
    srcs = ["get.cpp"],
)
