# please run `bazel run basic_content/c_poly:c_examp`
# please run `bazel run basic_content/c_poly:c++_examp`
load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "c_examp",
    srcs = ["c_examp.c"],
)

cc_binary(
    name = "c++_examp",
    srcs = ["c++_examp.cpp"],
)