# you can run some main program, just replace binary name
# such as: `bazel run basic_content/abstract:interesting_facts1`
#          `bazel run basic_content/abstract:interesting_facts2`
# etc...
load("@rules_cc//cc:defs.bzl", "cc_binary")

# Don't panic if you get compilation errors, this is what this code demonstrates, as expected.
cc_binary(
    name = "interesting_facts1",
    srcs = ["interesting_facts1.cpp"],
)

cc_binary(
    name = "interesting_facts2",
    srcs = ["interesting_facts2.cpp"],
)

# Don't panic if you get compilation errors, this is what this code demonstrates, as expected.
cc_binary(
    name = "interesting_facts3",
    srcs = ["interesting_facts3.cpp"],
)

cc_binary(
    name = "interesting_facts4",
    srcs = ["interesting_facts4.cpp"],
)

cc_binary(
    name = "interesting_facts5",
    srcs = ["interesting_facts5.cpp"],
)

# Don't panic if you get compilation errors, this is what this code demonstrates, as expected.
cc_binary(
    name = "pure_virtual",
    srcs = ["pure_virtual.cpp"],
)

cc_binary(
    name = "derived_full",
    srcs = ["derived_full.cpp"],
)