# please run `bazel run //practical_exercises/10_day_practice/day6/virtual_func:example`
# please run `bazel run //practical_exercises/10_day_practice/day6/virtual_func:virtual_feature`
# please run `bazel run //practical_exercises/10_day_practice/day6/virtual_func:virtual_dtor`
# please run `bazel run //practical_exercises/10_day_practice/day6/virtual_func:virtual`
# please run `bazel run //practical_exercises/10_day_practice/day6/virtual_func:vis`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "example",
    srcs = ["example.cpp"],
)
cc_binary(
    name = "virtual_feature",
    srcs = ["virtual_feature.cpp"],
)
cc_binary(
    name = "virtual_dtor",
    srcs = ["virtual_dtor.cpp"],
)
cc_binary(
    name = "virtual",
    srcs = ["virtual.cpp"],
)
cc_binary(
    name = "vis",
    srcs = ["vis.cpp"],
)
