# please run `bazel run //practical_exercises/10_day_practice/day2:rec1`
# please run `bazel run //practical_exercises/10_day_practice/day2:rec2`
# please run `bazel run //practical_exercises/10_day_practice/day2:hanoi`
# please run `bazel run //practical_exercises/10_day_practice/day2:st`
# please run `bazel run //practical_exercises/10_day_practice/day2:static`
# please run `bazel run //practical_exercises/10_day_practice/day2:shaizi`
# please run `bazel run //practical_exercises/10_day_practice/day2:pow`
# please run `bazel run //practical_exercises/10_day_practice/day2:compute`
# please run `bazel run //practical_exercises/10_day_practice/day2:enum`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "rec1",
    srcs = ["rec1.cpp"],
)
cc_binary(
    name = "rec2",
    srcs = ["rec2.cpp"],
)
cc_binary(
    name = "hanoi",
    srcs = ["hanoi.cpp"],
)
cc_binary(
    name = "st",
    srcs = ["st.cpp"],
)
cc_binary(
    name = "static",
    srcs = ["static.cpp"],
)
cc_binary(
    name = "shaizi",
    srcs = ["shaizi.cpp"],
)
cc_binary(
    name = "pow",
    srcs = ["pow.cpp"],
)
cc_binary(
    name = "compute",
    srcs = ["compute.cpp"],
)
cc_binary(
    name = "enum",
    srcs = ["enum.cpp"],
)
