# please run `bazel run //practical_exercises/10_day_practice/day8/class_template:stack`
# please run `bazel run //practical_exercises/10_day_practice/day8/class_template:spec`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "stack",
    srcs = ["stack.cpp"],
)
cc_binary(
    name = "spec",
    srcs = ["spec.cpp"],
)
