# please run `bazel run //practical_exercises/10_day_practice/day4/clock:operator`
# please run `bazel run //practical_exercises/10_day_practice/day4/clock:operator_plus`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "operator",
    srcs = ["operator.cpp"],
)
cc_binary(
    name = "operator_plus",
    srcs = ["operator_plus.cpp"],
)
