# please run `bazel run //design_pattern/producer_consumer:producer_consumer`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "producer_consumer",
    srcs = ["producer_consumer.cpp"],
)
