# please run `bazel run //concurrency/Threading_In_CPlusPlus/4.mutex:critical_section`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "critical_section",
    srcs = ["critical_section.cpp"],
    copts = ["-std=c++11"],
)
