# please run `bazel run //practical_exercises/10_day_practice/day8/func:3`
# please run `bazel run //practical_exercises/10_day_practice/day8/func:7-1`
# please run `bazel run //practical_exercises/10_day_practice/day8/func:6`
# please run `bazel run //practical_exercises/10_day_practice/day8/func:1`
# please run `bazel run //practical_exercises/10_day_practice/day8/func:9-2`
# please run `bazel run //practical_exercises/10_day_practice/day8/func:10`
# please run `bazel run //practical_exercises/10_day_practice/day8/func:2`
# please run `bazel run //practical_exercises/10_day_practice/day8/func:7`
# please run `bazel run //practical_exercises/10_day_practice/day8/func:5`
# please run `bazel run //practical_exercises/10_day_practice/day8/func:8`
# please run `bazel run //practical_exercises/10_day_practice/day8/func:9`
# please run `bazel run //practical_exercises/10_day_practice/day8/func:4`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "3",
    srcs = ["3.cpp"],
)
cc_binary(
    name = "7-1",
    srcs = ["7-1.cpp"],
)
cc_binary(
    name = "6",
    srcs = ["6.cpp"],
)
cc_binary(
    name = "1",
    srcs = ["1.cpp"],
)
cc_binary(
    name = "9-2",
    srcs = ["9-2.cpp"],
)
cc_binary(
    name = "10",
    srcs = ["10.cpp"],
)
cc_binary(
    name = "2",
    srcs = ["2.cpp"],
)
cc_binary(
    name = "7",
    srcs = ["7.cpp"],
)
cc_binary(
    name = "5",
    srcs = ["5.cpp"],
)
cc_binary(
    name = "8",
    srcs = ["8.cpp"],
)
cc_binary(
    name = "9",
    srcs = ["9.cpp"],
)
cc_binary(
    name = "4",
    srcs = ["4.cpp"],
)
