# please run `bazel run //codingStyleIdioms/3_RAII:RAII_fstram`
# please run `bazel run //codingStyleIdioms/3_RAII:c++_example1`
# please run `bazel run //codingStyleIdioms/3_RAII:c++_example`
# please run `bazel run //codingStyleIdioms/3_RAII:RAII`
# please run `bazel run //codingStyleIdioms/3_RAII:c_example`
# please run `bazel run //codingStyleIdioms/3_RAII:c++_example2`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "RAII_fstram",
    srcs = ["RAII_fstram.cpp"],
    copts = ["-std=c++11"],
)
cc_binary(
    name = "c++_example1",
    srcs = ["c++_example1.cpp"],
    copts = ["-std=c++11"],
)
cc_binary(
    name = "c++_example",
    srcs = ["c++_example.cpp"],
    copts = ["-std=c++11"],
)
cc_binary(
    name = "RAII",
    srcs = ["RAII.cpp"],
    copts = ["-std=c++11"],
)
cc_binary(
    name = "c_example",
    srcs = ["c_example.cpp"],
    copts = ["-std=c++11"],
)
cc_binary(
    name = "c++_example2",
    srcs = ["c++_example2.cpp"],
    copts = ["-std=c++11"],
)
