# please run `bazel run //practical_exercises/10_day_practice/day7/subscript_operator:subscript_operator`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "subscript_operator",
    srcs = ["subscript_operator.cpp"],
)
