# please run `bazel run //practical_exercises/10_day_practice/day4/friend:class`
# please run `bazel run //practical_exercises/10_day_practice/day4/friend:func`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "class",
    srcs = ["class.cpp"],
)
cc_binary(
    name = "func",
    srcs = ["func.cpp"],
)
