# please run `bazel run //practical_exercises/10_day_practice/day7/unary_operator:time_increase`
# please run `bazel run //practical_exercises/10_day_practice/day7/unary_operator:time_counter`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "time_increase",
    srcs = ["time_increase.cpp"],
)
cc_binary(
    name = "time_counter",
    srcs = ["time_counter.cpp"],
)
