# please run `bazel run //codingStyleIdioms/2_enumclass:namespace`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "namespace",
    srcs = ["namespace.cpp"],
    copts = ["-std=c++11"],
)
