# please run `bazel run //learn_class/modern_cpp_30/compilercompute:IF`
# please run `bazel run //learn_class/modern_cpp_30/compilercompute:factorial`
# please run `bazel run //learn_class/modern_cpp_30/compilercompute:fmap`
# please run `bazel run //learn_class/modern_cpp_30/compilercompute:WhileLoop`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "IF",
    srcs = ["IF.cpp"],
    copts = ["-std=c++17"],
)
cc_binary(
    name = "factorial",
    srcs = ["factorial.cpp"],
    copts = ["-std=c++17"],
)
cc_binary(
    name = "fmap",
    srcs = ["fmap.cpp"],
    copts = ["-std=c++17"],
)
cc_binary(
    name = "WhileLoop",
    srcs = ["WhileLoop.cpp"],
    copts = ["-std=c++17"],
)
