# please run `bazel run //design_pattern/observer_example:observer_example`

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "observer_example",
    srcs = ["observer_example.cpp"],
)